site_name: ferronj.github.io
#site_url: ferronj.github.io
theme:
  #name: simple-blog
  name: material
  features:
    - navigation.tabs
    - navigation.sections
plugins:
 - blog
 - jupyter

nav:
  - Home: index.md
  - Blog: blog/index.md
  - References: references.md
  - Showcase: showcase.md
  - Projects:
      - Conway's Game of Life: projects/conways_game_of_life.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
